import type {
  CatalogProduct,
  CostSummary,
  PortalUser,
  ProductRecommendation,
  RenewalItem,
  Subscription,
  UserRollup,
} from "./types";

export const CURRENT_ADMIN = "admin@netrichtechnologies.com";

export const renewals: RenewalItem[] = [
  {
    id: "r1",
    productName: "Microsoft 365 Business Basic (no Teams)",
    licenses: 130,
    commitment: "Annual commit",
    billing: "Billed Monthly",
    renewalDate: "2026-09-23",
  },
  {
    id: "r2",
    productName: "Microsoft 365 Business Standard (no Teams)",
    licenses: 1,
    commitment: "Annual commit",
    billing: "Billed Monthly",
    renewalDate: "2027-06-25",
  },
];

export const userRollup: UserRollup = {
  active: 174,
  pending: 0,
  blocked: 6,
  error: 0,
};

export const recommendations: ProductRecommendation[] = [
  {
    id: "rec1",
    name: "Enterprise Mobility + Security E5",
    status: "Not Purchased",
    initials: "EM",
  },
  {
    id: "rec2",
    name: "Exchange Online (Plan 1)",
    status: "Not Purchased",
    initials: "EO",
  },
];

export const costSummary: CostSummary = {
  monthly: 666.02,
  yearly: 0,
  triennially: 0,
};

export const subscriptions: Subscription[] = [
  {
    id: "sub1",
    name: "Microsoft 365 Business Basic (no Teams)",
    description:
      "Best for businesses that need professional email, cloud file storage, and online meetings & chat. Desktop versions of Office apps like Outlook, Word, Excel, and PowerPoint not included.",
    category: "business",
    purchased: 130,
    used: 130,
    available: 0,
    billingCycle: "Monthly",
    commitment: "Annual",
    price: 655.2,
    nextRenewal: "2026-09-23",
    skuId: "3b555118-da6a-4418-936f-0779df01befb",
  },
  {
    id: "sub2",
    name: "Microsoft 365 Business Standard (no Teams)",
    description:
      "Best for businesses that need Office apps across devices plus professional email, cloud file storage, and online meetings & chat.",
    category: "business",
    purchased: 1,
    used: 1,
    available: 0,
    billingCycle: "Monthly",
    commitment: "Annual",
    price: 10.82,
    nextRenewal: "2027-06-25",
    hasAlert: true,
    skuId: "f245ecc8-75af-4f8e-b61f-37d14710ea4b",
  },
];

export const users: PortalUser[] = [
  {
    id: "u1",
    displayName: "Ahmed Hassan",
    email: "ahmed.hassan@netrichtechnologies.onmicrosoft.com",
    status: "active",
    licenses: ["Microsoft 365 Business Basic (no Teams)"],
    syncedFromGraph: true,
    lastSyncedAt: "2026-09-02T08:00:00Z",
  },
  {
    id: "u2",
    displayName: "Sara Al-Rashid",
    email: "sara.alrashid@netrichtechnologies.onmicrosoft.com",
    status: "active",
    licenses: ["Microsoft 365 Business Basic (no Teams)"],
    syncedFromGraph: true,
    lastSyncedAt: "2026-09-02T08:00:00Z",
  },
  {
    id: "u3",
    displayName: "Omar Barkan",
    email: "omar.barkan@netrichtechnologies.onmicrosoft.com",
    status: "active",
    licenses: ["Microsoft 365 Business Standard (no Teams)"],
    syncedFromGraph: true,
    lastSyncedAt: "2026-09-02T08:00:00Z",
  },
  {
    id: "u4",
    displayName: "Layla Mansour",
    email: "layla.mansour@netrichtechnologies.onmicrosoft.com",
    status: "blocked",
    licenses: ["Microsoft 365 Business Basic (no Teams)"],
    syncedFromGraph: true,
    lastSyncedAt: "2026-09-02T08:00:00Z",
  },
  {
    id: "u5",
    displayName: "Youssef Nader",
    email: "youssef.nader@netrichtechnologies.onmicrosoft.com",
    status: "active",
    licenses: ["Microsoft 365 Business Basic (no Teams)"],
    syncedFromGraph: true,
    lastSyncedAt: "2026-09-02T08:00:00Z",
  },
  {
    id: "u6",
    displayName: "Nour Ibrahim",
    email: "nour.ibrahim@netrichtechnologies.onmicrosoft.com",
    status: "active",
    licenses: ["Microsoft 365 Business Basic (no Teams)"],
    syncedFromGraph: true,
    lastSyncedAt: "2026-09-02T08:00:00Z",
  },
  {
    id: "u7",
    displayName: "Karim Farouk",
    email: "karim.farouk@netrichtechnologies.onmicrosoft.com",
    status: "blocked",
    licenses: [],
    syncedFromGraph: true,
    lastSyncedAt: "2026-09-02T08:00:00Z",
  },
  {
    id: "u8",
    displayName: "Hana Saleh",
    email: "hana.saleh@netrichtechnologies.onmicrosoft.com",
    status: "active",
    licenses: ["Microsoft 365 Business Basic (no Teams)"],
    syncedFromGraph: true,
    lastSyncedAt: "2026-09-02T08:00:00Z",
  },
];

export const microsoft365Catalog: CatalogProduct[] = [
  {
    id: "m365-1",
    name: "Microsoft 365 Business Basic (no Teams)",
    description:
      "Professional email, 1 TB OneDrive, SharePoint, and web/mobile versions of Office apps.",
    category: "Microsoft 365 Suites",
    catalog: "microsoft-365",
    status: "purchased",
    qty: 130,
    priceMonthly: 5.76,
    priceYearly: null,
    compatibleAddons: true,
    filters: ["Email Security", "Microsoft 365 Suites", "All Microsoft 365 Products"],
  },
  {
    id: "m365-2",
    name: "Microsoft 365 Business Standard (no Teams)",
    description:
      "Desktop Office apps, email, OneDrive, SharePoint, and collaboration tools.",
    category: "Microsoft 365 Suites",
    catalog: "microsoft-365",
    status: "purchased",
    qty: 1,
    priceMonthly: 10.82,
    priceYearly: null,
    compatibleAddons: true,
    filters: ["Microsoft 365 Suites", "Office Apps & Services", "All Microsoft 365 Products"],
  },
  {
    id: "m365-3",
    name: "Microsoft 365 Business Premium",
    description:
      "Advanced security, device management, and desktop Office apps for businesses.",
    category: "Microsoft 365 Suites",
    catalog: "microsoft-365",
    status: "available",
    qty: 0,
    priceMonthly: 21.0,
    priceYearly: 252.0,
    compatibleAddons: true,
    filters: ["Microsoft 365 Suites", "Security & Identity", "All Microsoft 365 Products"],
  },
  {
    id: "m365-4",
    name: "Exchange Online (Plan 1)",
    description: "Business-class email hosted on Exchange Online with 50 GB mailbox.",
    category: "Email",
    catalog: "microsoft-365",
    status: "available",
    qty: 0,
    priceMonthly: 3.84,
    priceYearly: 46.08,
    filters: ["Email Security", "All Microsoft 365 Products"],
  },
  {
    id: "m365-5",
    name: "Microsoft Teams Essentials",
    description: "Meetings, chat, and collaboration for small businesses.",
    category: "Teams & Voice",
    catalog: "microsoft-365",
    status: "available",
    qty: 0,
    priceMonthly: 3.84,
    priceYearly: 46.08,
    filters: ["Teams & Voice", "All Microsoft 365 Products"],
  },
  {
    id: "m365-6",
    name: "Microsoft Defender for Office 365 Plan 1",
    description: "Advanced threat protection for email and collaboration tools.",
    category: "Security",
    catalog: "microsoft-365",
    status: "available",
    qty: 0,
    priceMonthly: 1.92,
    priceYearly: 23.04,
    filters: ["Email Security", "Security & Identity", "All Microsoft 365 Products"],
  },
  {
    id: "m365-7",
    name: "Power Automate per user plan",
    description: "Automate workflows across Microsoft 365 and third-party apps.",
    category: "Power Platform",
    catalog: "microsoft-365",
    status: "available",
    qty: 0,
    priceMonthly: 14.4,
    priceYearly: 172.8,
    filters: ["Power Platform", "All Microsoft 365 Products"],
  },
  {
    id: "m365-8",
    name: "Enterprise Mobility + Security E5",
    description: "Identity, device, and information protection with advanced threat analytics.",
    category: "Security",
    catalog: "microsoft-365",
    status: "not-purchased",
    qty: 0,
    priceMonthly: 15.84,
    priceYearly: 190.08,
    filters: ["Security & Identity", "All Microsoft 365 Products"],
  },
];

export const dynamics365Catalog: CatalogProduct[] = [
  {
    id: "d365-1",
    name: "AI Builder Capacity add-on",
    description: "Additional AI Builder capacity for Power Platform solutions.",
    category: "Power Platform",
    catalog: "dynamics-365",
    status: "available",
    qty: 0,
    priceMonthly: 600.0,
    priceYearly: 7200.0,
    attachMonthly: null,
    attachYearly: null,
    filters: ["Power Platform", "All Dynamics 365 Products"],
  },
  {
    id: "d365-2",
    name: "Dynamics 365 Sales Professional",
    description: "CRM for sales teams to manage leads, opportunities, and customer relationships.",
    category: "CRM",
    catalog: "dynamics-365",
    status: "available",
    qty: 0,
    priceMonthly: 62.4,
    priceYearly: 748.8,
    attachMonthly: 19.2,
    attachYearly: 230.4,
    filters: ["CRM", "All Dynamics 365 Products"],
  },
  {
    id: "d365-3",
    name: "Dynamics 365 Customer Service Professional",
    description: "Customer service tools for case management and knowledge base.",
    category: "CRM",
    catalog: "dynamics-365",
    status: "available",
    qty: 0,
    priceMonthly: 48.0,
    priceYearly: 576.0,
    attachMonthly: 19.2,
    attachYearly: 230.4,
    filters: ["CRM", "All Dynamics 365 Products"],
  },
  {
    id: "d365-4",
    name: "Dynamics 365 Business Central Essentials",
    description: "ERP for finance, supply chain, and operations for growing businesses.",
    category: "ERP",
    catalog: "dynamics-365",
    status: "available",
    qty: 0,
    priceMonthly: 67.2,
    priceYearly: 806.4,
    attachMonthly: 38.4,
    attachYearly: 460.8,
    filters: ["ERP", "All Dynamics 365 Products"],
  },
  {
    id: "d365-5",
    name: "Power Apps per user plan",
    description: "Build and run custom business apps across web and mobile.",
    category: "Power Platform",
    catalog: "dynamics-365",
    status: "available",
    qty: 0,
    priceMonthly: 19.2,
    priceYearly: 230.4,
    filters: ["Power Platform", "Recommended for you", "All Dynamics 365 Products"],
  },
];

export const azureCatalog: CatalogProduct[] = [
  {
    id: "az-1",
    name: "Azure Plan",
    description: "Pay-as-you-go Azure consumption through netrichtechnologies CSP.",
    category: "Azure",
    catalog: "azure",
    status: "available",
    qty: 0,
    priceMonthly: 0,
    priceYearly: null,
    filters: ["All Azure Products"],
  },
  {
    id: "az-2",
    name: "Azure Active Directory Premium P1",
    description: "Advanced identity and access management capabilities.",
    category: "Identity",
    catalog: "azure",
    status: "available",
    qty: 0,
    priceMonthly: 5.76,
    priceYearly: 69.12,
    filters: ["All Azure Products"],
  },
];

export const serverSoftwareCatalog: CatalogProduct[] = [
  {
    id: "srv-1",
    name: "Windows Server Standard Core",
    description: "Windows Server Standard edition licensed by core.",
    category: "Server",
    catalog: "server-software",
    status: "available",
    qty: 0,
    priceMonthly: 0,
    priceYearly: 1067.0,
    filters: ["All Server Software"],
  },
  {
    id: "srv-2",
    name: "SQL Server Standard Core",
    description: "SQL Server Standard edition for relational databases.",
    category: "Database",
    catalog: "server-software",
    status: "available",
    qty: 0,
    priceMonthly: 0,
    priceYearly: 3586.0,
    filters: ["All Server Software"],
  },
];
