/** Shared with Next BFF — mirror of backend/libs/rbac.ts */
export const PERMISSIONS = [
  { key: "tenant.read", description: "View customers/tenants" },
  { key: "tenant.create", description: "Create customers" },
  { key: "tenant.suspend", description: "Suspend customers" },
  { key: "tenant.delete", description: "Request delete / terminate" },
  { key: "user.read", description: "View portal/directory users" },
  { key: "user.create", description: "Create users" },
  { key: "user.disable", description: "Disable users" },
  { key: "user.license.assign", description: "Assign licenses" },
  { key: "subscription.read", description: "View subscriptions" },
  { key: "subscription.purchase", description: "Purchase subscriptions" },
  { key: "subscription.quantity.change", description: "Change seats" },
  { key: "subscription.cancel", description: "Cancel subscriptions" },
  { key: "quote.read", description: "View quotes" },
  { key: "quote.create", description: "Generate quotes" },
  { key: "invoice.read", description: "View invoices" },
  { key: "invoice.create", description: "Generate invoices" },
  { key: "invoice.write", description: "Update invoice status" },
  { key: "invoice.download", description: "Download invoices" },
  { key: "security.read", description: "View security center" },
  { key: "support.read", description: "View support tickets" },
  { key: "support.respond", description: "Respond to support" },
  { key: "audit.read", description: "View audit logs" },
  { key: "gdap.read", description: "View GDAP" },
  { key: "gdap.manage", description: "Manage GDAP" },
  { key: "platform.admin", description: "Platform administration" },
  { key: "admin.impersonate", description: "View-as-customer" },
] as const;

export const ROLE_PACKS = [
  {
    key: "platform_super_admin",
    name: "Platform Super Admin",
    scope: "partner" as const,
    permissions: PERMISSIONS.map((p) => p.key),
  },
  {
    key: "partner_operations_admin",
    name: "Partner Operations Admin",
    scope: "partner" as const,
    permissions: [
      "tenant.read",
      "tenant.create",
      "tenant.suspend",
      "user.read",
      "user.create",
      "subscription.read",
      "quote.read",
      "quote.create",
      "invoice.read",
      "invoice.create",
      "invoice.write",
      "gdap.read",
      "gdap.manage",
      "support.read",
      "audit.read",
      "admin.impersonate",
    ],
  },
  {
    key: "customer_global_admin",
    name: "Customer Global Admin",
    scope: "customer" as const,
    permissions: [
      "user.read",
      "user.create",
      "user.disable",
      "user.license.assign",
      "subscription.read",
      "subscription.purchase",
      "invoice.read",
      "security.read",
      "support.read",
      "support.respond",
    ],
  },
];

export const LEGACY_ROLE_MAP: Record<string, string> = {
  partner_admin: "platform_super_admin",
  support_technical: "partner_support_admin",
  support_billing: "partner_billing_admin",
  customer_admin: "customer_global_admin",
};
